using UnityEngine;

public class PauseMenu : MonoBehaviour
{
    public GameObject pauseUI;  
    private bool isPaused = false;

    void Update()
    {
        if (Input.GetKeyDown(KeyCode.Escape))
        {
            if (isPaused)
                Resume();
            else
                Pause();
        }
    }

    public void Resume()
    {
        pauseUI.SetActive(false);
        Time.timeScale = 1f;     
        isPaused = false;
    }

    void Pause()
    {
        pauseUI.SetActive(true);
        Time.timeScale = 0f;     
        isPaused = true;
    }


    public void QuitGame()
    {
        Application.Quit();
    }
}
